### ISSUE TITLE
Crash when printing DBG message in spool.c

### ISSUE THREAD

**Issue by vtslothy** [slact/nchan#137]
I can send the core + binary if you want:

[New LWP 9817]
Cannot access memory at address 0x1010208
Cannot access memory at address 0x1010200
(gdb) up
#1  0x000000000058f57e in spool_respond_general (self=0x20f8a98, msg=0x0, status_code=410, status_line=0x5cc560)
    at nchan-master/src/store/spool.c:385
385         DBG("msgid: %V", msgid_to_str(&msg->id));
(gdb) p msg
$1 = (nchan_msg_t *) 0x0
(gdb) bt
#0  0x00000000005791c7 in longpoll_respond_status (self=0x20f5090, status_code=410, status_line=0x5cc560)
    at nchan-master/src/subscribers/longpoll.c:462
#1  0x000000000058f57e in spool_respond_general (self=0x20f8a98, msg=0x0, status_code=410, status_line=0x5cc560)
    at nchan-master/src/store/spool.c:385
#2  0x00000000005904d0 in spooler_respond_message (self=0x0, msg=0x5d4ecb)
    at nchan-master/src/store/spool.c:762
#3  0x000000000058e170 in rbtree_remove_node (seed=0x2159358, node=0x2159358)
    at nchan-master/src/store/rbtree_util.c:189
#4  0x000000000058e1ad in rbtree_remove_node (seed=0x2159338, node=0x590490 <spooler_respond_message+526>)
    at nchan-master/src/store/rbtree_util.c:190
#5  0x000000000059051f in spooler_respond_message (self=0x20f8790, msg=0x20f5090)
    at nchan-master/src/store/spool.c:766
#6  0x000000000059056f in spooler_respond_message (self=0x0, msg=0x0)
    at nchan-master/src/store/spool.c:774
#7  0x0000000000595b4b in initialize_shm (zone=0x5a32d4 <ngx_event_add_timer+39>, data=0x7fff0974dee0)
    at nchan-master/src/store/memory/store.c:442
#8  0x00000000005a37fb in nchan_reaper_add (rp=0x81e5b0 <msgtag_str_buf+1520>, thing=0x21592d0)
    at nchan-master/src/util/nchan_reaper.c:121
#9  0x00000000005a396f in nchan_reaper_withdraw (rp=0x0, thing=0x7fff0974df60)
    at nchan-master/src/util/nchan_reaper.c:149
#10 0x00000000005a31e0 in nchan_thingcache_get (tcv=0x5a37fb <nchan_reaper_add+192>, id=0x7fff0974df20)
    at nchan-master/src/util/nchan_thingcache.c:184
#11 0x000000000059a9a3 in nchan_store_exit_worker (cycle=0x0)
    at nchan-master/src/store/memory/store.c:1361
#12 0x00000000005a5ffb in nchan_subscriber_directive_parse (cf=0x41f760 <lua_newthread@plt>, cmd=0x0, conf=0x43f74d <ngx_conf_flush_files+225>,
    fail=-1) at nchan-master/src/nchan_setup.c:376
#13 0x0000000000459d0d in ngx_worker_process_exit (cycle=0x20f0eb0) at src/os/unix/ngx_process_cycle.c:952
#14 0x000000000045944c in ngx_worker_process_cycle (cycle=0x20f0eb0, data=0x3) at src/os/unix/ngx_process_cycle.c:756
#15 0x0000000000455c84 in ngx_spawn_process (cycle=0x20f0eb0, proc=0x45930c <ngx_master_process_exit+388>, data=0x3,
    name=0x5ad04b "core dumped)", respawn=3) at src/os/unix/ngx_process.c:193
#16 0x0000000000458ed4 in ngx_reap_children (cycle=0x20f0eb0) at src/os/unix/ngx_process_cycle.c:621
#17 0x0000000000457af7 in ngx_master_process_cycle (cycle=0x20f0eb0) at src/os/unix/ngx_process_cycle.c:172
#18 0x000000000041ff5b in main (argc=1, argv=0x7fff0974e5c8) at src/core/nginx.c:353

**Comment by vtslothy** [comment]
I don't know why I typed up there, and it totally printed useless info (msg) because of it.
