### ISSUE TITLE
Program terminated with signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#173]
Someone told me there was a problem at about 11:15 and I saw that a nginx worker crashed this morning.

The last core dump was at 10:23:02 but nchan wasn't reporting the right data  when I checked at 11:15 just before restarting so I'm thinking that maybe nchan didn't recover after the crashes and wasn't working properly.

The log wasn't in debug mode and nginx was compiled the same way from the deb package that they provide (not the way we did the last time I gave you core dumps).

nginx-1.9.15
nchan 3e439ed4594ca14934b7c90631b8125050da75de

```
$ ls -l /var/crash/
total 5568
-rw-r----- 1 www-data whoopsie 5699395 mai  2 07:44 _usr_sbin_nginx.33.crash
```

error log
```
2016/05/02 06:46:00 [info] 1698#1698: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 06:51:00 [info] 3249#3249: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 06:56:01 [info] 4743#4743: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:01:00 [info] 6291#6291: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:06:00 [info] 7744#7744: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:11:00 [info] 9158#9158: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:16:00 [info] 10608#10608: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:21:00 [info] 12058#12058: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:26:01 [info] 13520#13520: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:31:00 [info] 14939#14939: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:36:00 [info] 16362#16362: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:41:00 [info] 17802#17802: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:44:10 [alert] 18280#18280: worker process 30858 exited on signal 11 (core dumped)
2016/05/02 07:44:10 [error] 18361#18361: IPC:got IPC alert delayed by 5 sec
2016/05/02 07:44:10 [error] 380#380: SPOOL:Unexpected spool == nuspool during spool fetch_msg_callback. This is weird, please report this to the developers. findmsg_status: 3
2016/05/02 07:44:10 [error] 18361#18361: IPC:got IPC alert delayed by 4 sec
ker process: /home/bbigras/nginx/nginx-1.9.15/debian/modules/nchan-0.99.12/src/store/spool.c:238: spool_fetch_msg_callback: Assertion `0' failed.
2016/05/02 07:44:11 [alert] 18280#18280: worker process 380 exited on signal 6 (core dumped)
2016/05/02 07:44:11 [alert] 18280#18280: worker process 18363 exited on signal 11 (core dumped)
2016/05/02 07:44:42 [alert] 18280#18280: worker process 18365 exited on signal 11 (core dumped)
2016/05/02 07:45:13 [error] 18361#18361: SPOOL:Unexpected spool == nuspool during spool fetch_msg_callback. This is weird, please report this to the developers. findmsg_status: 3
ker process: /home/bbigras/nginx/nginx-1.9.15/debian/modules/nchan-0.99.12/src/store/spool.c:238: spool_fetch_msg_callback: Assertion `0' failed.
2016/05/02 07:45:13 [alert] 18280#18280: worker process 18361 exited on signal 6 (core dumped)
2016/05/02 07:46:01 [info] 19251#19251: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:51:00 [info] 20712#20712: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 07:56:00 [info] 22163#22163: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:01:01 [info] 23783#23783: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:06:00 [info] 25211#25211: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:11:01 [info] 26664#26664: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:16:00 [info] 28089#28089: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:21:01 [info] 29562#29562: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:26:01 [info] 31011#31011: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:31:00 [info] 32477#32477: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:36:00 [info] 1508#1508: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:41:00 [info] 3048#3048: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:46:00 [info] 4476#4476: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:51:01 [info] 6032#6032: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 08:56:00 [info] 7493#7493: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:01:01 [info] 9089#9089: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:06:01 [info] 10598#10598: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:11:00 [info] 12037#12037: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:16:00 [info] 13482#13482: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:21:00 [info] 14898#14898: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:26:02 [info] 16341#16341: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:31:00 [info] 17761#17761: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:36:01 [info] 19214#19214: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:41:01 [info] 20648#20648: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:46:00 [info] 22111#22111: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:51:00 [info] 23530#23530: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 09:56:00 [info] 24969#24969: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:01:00 [info] 26546#26546: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:04:12 [error] 18478#18478: NCHAN MSG_ID:verify_msg_id: not a multimsg tag, different times. could be a missed message.
2016/05/02 10:04:12 [error] 18478#18478: NCHAN MSG_ID:missed a message for an unknown reason. Maybe it's a bug or maybe the message queue length is too small.
2016/05/02 10:06:01 [info] 27988#27988: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:11:00 [info] 29418#29418: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:16:00 [info] 30885#30885: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:21:00 [info] 32346#32346: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:23:02 [alert] 18280#18280: worker process 18478 exited on signal 11 (core dumped)
2016/05/02 10:26:02 [info] 1396#1396: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:31:02 [info] 7298#7298: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:36:01 [info] 9000#9000: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:41:01 [info] 10493#10493: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:46:01 [info] 11956#11956: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:51:01 [info] 13359#13359: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 10:56:01 [info] 14814#14814: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 11:01:01 [info] 16360#16360: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 11:06:01 [info] 17809#17809: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 11:11:01 [info] 19229#19229: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 11:16:01 [info] 20797#20797: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 11:16:06 [error] 32675#32675: REDISTORE: SYNC add_fakesub command
2016/05/02 11:21:01 [info] 22268#22268: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/05/02 11:26:02 [info] 23813#23813: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
```

```
$ gdb `which nginx` CoreDump
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/nginx...Reading symbols from /usr/lib/debug/.build-id/7c/6f589235091c270b13731c005969fc22f4c29d.debug...done.
done.
[New LWP 30858]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                   '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x080f880e in nx_find_wl_in_hash (mstr=mstr@entry=0x8823150, cf=cf@entry=0x86ea644, zone=zone@entry=HEADERS) at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_runtime.c:342
342         mstr->data[i] = tolower(mstr->data[i]);
(gdb) bt
#0  0x080f880e in nx_find_wl_in_hash (mstr=mstr@entry=0x8823150, cf=cf@entry=0x86ea644, zone=zone@entry=HEADERS) at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_runtime.c:342
#1  0x080f8d5c in ngx_http_dummy_is_rule_whitelisted_n (req=req@entry=0x88225c8, cf=cf@entry=0x86ea644, r=r@entry=0x86c32a4, name=name@entry=0x8823150, zone=zone@entry=HEADERS,
    target_name=target_name@entry=0) at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_runtime.c:629
#2  0x080fa5b7 in ngx_http_apply_rulematch_v_n (r=r@entry=0x86c32a4, ctx=ctx@entry=0x882330c, req=req@entry=0x88225c8, name=name@entry=0x8823150, value=value@entry=0x8823158, zone=zone@entry=HEADERS,
    nb_match=0, target_name=target_name@entry=0) at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_runtime.c:1030
#3  0x080faf0c in ngx_http_basestr_ruleset_n (pool=0x88225a0, name=name@entry=0x8823150, value=value@entry=0x8823158, rules=0x86bd8c0, req=req@entry=0x88225c8, ctx=ctx@entry=0x882330c,
    zone=zone@entry=HEADERS) at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_runtime.c:1397
#4  0x080fb2e3 in ngx_http_dummy_headers_parse (main_cf=main_cf@entry=0x85b8598, cf=cf@entry=0x86ea644, ctx=ctx@entry=0x882330c, r=r@entry=0x88225c8)
    at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_runtime.c:2078
#5  0x080fcd98 in ngx_http_dummy_data_parse (ctx=ctx@entry=0x882330c, r=r@entry=0x88225c8) at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_runtime.c:2102
#6  0x080fed3f in ngx_http_dummy_access_handler (r=0x88225c8) at /home/bbigras/nginx/nginx-1.9.15/debian/modules/naxsi/naxsi_src/naxsi_skeleton.c:1228
#7  0x080973c3 in ngx_http_core_rewrite_phase (r=0x88225c8, ph=0x879df94) at src/http/ngx_http_core_module.c:901
#8  0x08092e29 in ngx_http_core_run_phases (r=0x88225c8) at src/http/ngx_http_core_module.c:847
#9  0x080c62f8 in ngx_http_v2_process_request_body (r=0x88225c8, pos=pos@entry=0x87bf711 "{\"Nom\":\"M05021\",\"Type\":\"NonPeinte\"}\320b\r&=LtA\352\373$\343\261\005L\034\067\341Y\357Ր؂ڇ",
    size=size@entry=35, last=1) at src/http/v2/ngx_http_v2.c:3587
#10 0x080c7513 in ngx_http_v2_state_read_data (h2c=0x86a5720, pos=0x87bf711 "{\"Nom\":\"M05021\",\"Type\":\"NonPeinte\"}\320b\r&=LtA\352\373$\343\261\005L\034\067\341Y\357Ր؂ڇ",
    end=0x87bf734 "\320b\r&=LtA\352\373$\343\261\005L\034\067\341Y\357Ր؂ڇ") at src/http/v2/ngx_http_v2.c:922
#11 0x080c8a0a in ngx_http_v2_read_handler (rev=<optimized out>) at src/http/v2/ngx_http_v2.c:362
#12 0x0807f78c in ngx_event_process_posted (cycle=<optimized out>, cycle@entry=0x85b64b8, posted=<optimized out>) at src/event/ngx_event_posted.c:33
#13 0x0807f35a in ngx_process_events_and_timers (cycle=cycle@entry=0x85b64b8) at src/event/ngx_event.c:259
#14 0x08085976 in ngx_worker_process_cycle (cycle=0x85b64b8, data=0x0) at src/os/unix/ngx_process_cycle.c:753
#15 0x080843a6 in ngx_spawn_process (cycle=cycle@entry=0x85b64b8, proc=0x80858f0 <ngx_worker_process_cycle>, data=0x0, name=0x8171fbb "worker process", respawn=respawn@entry=2)
    at src/os/unix/ngx_process.c:198
#16 0x080869f2 in ngx_reap_children (cycle=0x85b64b8) at src/os/unix/ngx_process_cycle.c:621
#17 ngx_master_process_cycle (cycle=<optimized out>, cycle@entry=0x85b2498) at src/os/unix/ngx_process_cycle.c:174
#18 0x080633de in main (argc=3, argv=0xbf8d5dd4) at src/core/nginx.c:367
```

**Comment by brunoqc** [comment]
I'm an idiot. It's not a nchan crash. Sorry about that.

**Comment by brunoqc** [comment]
But there was some errors about nchan, like :

```
2016/05/02 07:45:13 [error] 18361#18361: SPOOL:Unexpected spool == nuspool during spool fetch_msg_callback. This is weird, please report this to the developers. findmsg_status: 3
ker process: /home/bbigras/nginx/nginx-1.9.15/debian/modules/nchan-0.99.12/src/store/spool.c:238: spool_fetch_msg_callback: Assertion `0' failed.
```

**Comment by slact** [comment]
No problem. Nchan is currently (intentionally) not robust after a worker  crashes, that way I get more bug reports even for the smallest of errors. This is a decision I made for the beta release. So if something else crashed an nchan worker, it may lead to undefined behavior in other workers. If you see that error again without a prior crash, I'll look into in. Otherwise, for now I'll just keep an eye on it.
