### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#198]
I just got this random crash.

nginx/1.11.1
nchan 0.99.16

```
Reading symbols from /usr/sbin/nginx...Reading symbols from /usr/lib/debug/.build-id/22/52597e56bb163e96e29c7a63ff78829cb2444d.debug...done.
done.
[New LWP 9255]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                   '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ngx_rbtree_min (sentinel=0x8203a10 <ngx_event_timer_sentinel>, node=0x0) at src/core/ngx_rbtree.h:74
74          while (node->left != sentinel) {
(gdb) bt
#0  ngx_rbtree_min (sentinel=0x8203a10 <ngx_event_timer_sentinel>, node=0x0) at src/core/ngx_rbtree.h:74
#1  ngx_event_find_timer () at src/event/ngx_event_timer.c:45
#2  0x0807facd in ngx_process_events_and_timers (cycle=cycle@entry=0x9f8e4e8) at src/event/ngx_event.c:204
#3  0x08086216 in ngx_worker_process_cycle (cycle=0x9f8e4e8, data=0x1) at src/os/unix/ngx_process_cycle.c:753
#4  0x08084c46 in ngx_spawn_process (cycle=cycle@entry=0x9f8e4e8, proc=proc@entry=0x8086190 <ngx_worker_process_cycle>, data=data@entry=0x1, name=name@entry=0x8174f9f "worker process",
    respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:198
#5  0x080863f3 in ngx_start_worker_processes (cycle=cycle@entry=0x9f8e4e8, n=2, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:358
#6  0x08086de0 in ngx_master_process_cycle (cycle=cycle@entry=0x9f8e4e8) at src/os/unix/ngx_process_cycle.c:130
#7  0x080639ae in main (argc=3, argv=0xbf8c2a64) at src/core/nginx.c:367
```

```
2016/06/21 15:40:19 [error] 9255#9255: REDIS_REPLY_ERROR: Subscriber count for channel /apresPost less than zero: -1
2016/06/21 15:40:40 [notice] 16749#16749: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:5
2016/06/21 15:40:40 [notice] 16749#16749: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:5
2016/06/21 15:40:40 [notice] 16749#16749: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:14
2016/06/21 15:40:40 [notice] 16749#16749: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:14
2016/06/21 15:40:40 [info] 16749#16749: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/06/21 15:41:16 [alert] 9253#9253: worker process 9255 exited on signal 11 (core dumped)
2016/06/21 15:41:16 [error] 16882#16882: IPC:got IPC alert delayed by 9 sec
2016/06/21 15:45:40 [notice] 18412#18412: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:5
2016/06/21 15:45:40 [notice] 18412#18412: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:5
2016/06/21 15:45:40 [notice] 18412#18412: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:14
2016/06/21 15:45:40 [notice] 18412#18412: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:14
2016/06/21 15:45:40 [info] 18412#18412: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
```

**Comment by brunoqc** [comment]
It's not even related to nchan. Sorry about that, again.

**Comment by slact** [comment]
No problem
