### ISSUE TITLE
Crash after POSTing a message then disconnecting before response

### ISSUE THREAD

**Issue by bymaximus** [slact/nchan#235]
Hi my friend, any ideia? Running negam with redis and websocket subscribers, I can provide more data if needed.

```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/nginx...done.
[New LWP 16024]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                           '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ngx_palloc (pool=0x0, size=80) at src/core/ngx_palloc.c:126
126	    if (size <= pool->max) {

Thread 1 (Thread 0x7f34c01de740 (LWP 16024)):
#0  ngx_palloc (pool=0x0, size=80) at src/core/ngx_palloc.c:126
No locals.
#1  0x0000556bb6c5dd3e in ngx_pcalloc (pool=<optimized out>, 
    size=size@entry=80) at src/core/ngx_palloc.c:302
        p = <optimized out>
#2  0x0000556bb6d5f64d in nchan_respond_string (r=0x556bb84b1a00, 
    status_code=200, 
    content_type=0x556bb7291850 <channel_info_content_type>, 
    body=body@entry=0x7ffdc426f820, finalize=0)
    at /root/nchan/src/util/nchan_output.c:531
        rc = 0
        b = <optimized out>
        chain = <optimized out>
#3  0x0000556bb6d5f807 in nchan_respond_membuf (r=r@entry=0x556bb84b1a00, 
    status_code=status_code@entry=200, content_type=<optimized out>, 
    body=<optimized out>, finalize=finalize@entry=0)
    at /root/nchan/src/util/nchan_output.c:338
        str = {len = 85, 
          data = 0x556bb7291600 <channel_info_buf_str> "{\"messages\": 0, \"requested\": 0, \"subscribers\": 2, \"last_message_id\": \"1472092167:1\" }"}
#4  0x0000556bb6d61751 in nchan_channel_info (r=r@entry=0x556bb84b1a00, 
    messages=<optimized out>, subscribers=<optimized out>, 
    last_seen=<optimized out>, msgid=<optimized out>)
    at /root/nchan/src/util/nchan_channel_info.c:103
        b = <optimized out>
        content_type = 0x556bb7291850 <channel_info_content_type>
        accept_header = <optimized out>
#5  0x0000556bb6d6179b in nchan_response_channel_ptr_info (
    channel=channel@entry=0x7ffdc426f890, r=r@entry=0x556bb84b1a00, 
    status_code=<optimized out>)
    at /root/nchan/src/util/nchan_channel_info.c:126
        CREATED_LINE = {len = 11, data = 0x556bb6d9fb93 "201 Created"}
        ACCEPTED_LINE = {len = 12, data = 0x556bb6d9fb9f "202 Accepted"}
        last_seen = <optimized out>
        subscribers = <optimized out>
        messages = <optimized out>
        msgid = 0x7ffdc426f8c0
#6  0x0000556bb6d93988 in publish_callback (status=<optimized out>, 
    rptr=0x7ffdc426f890, r=0x556bb84b1a00)
    at /root/nchan/src/nchan_module.c:432
        ch = <optimized out>
        ctx = 0x556bb847f288
        empty_msgid = {time = 0, tag = {fixed = {0, 0, 0, 0}, allocd = 0x0}, 
          tagactive = 0, tagcount = 0}
#7  0x0000556bb6d873bd in receive_publish_message_reply (
    sender=<optimized out>, d=0x7ffdc426f910)
    at /root/nchan/src/store/memory/ipc-handlers.c:385
        ch = {id = {len = 93921140507072, 
            data = 0x556bb8288900 "\360\211(\270kU"}, messages = 0, 
          subscribers = 2, last_seen = 1472092167, expires = 93921116536493, 
          last_published_msg_id = {time = 1472092167, tag = {fixed = {1, 
                -18357, 21867, 0}, allocd = 0x556bb84b0001}, tagactive = 0, 
            tagcount = 1}}
#8  0x0000556bb6d86a07 in ipc_read_handler (ev=0x556bb8377e60)
    at /root/nchan/src/store/memory/ipc.c:449
        alert = {
          data = "(#\000\000\002\000\000\000\000\000\021\270kU\000\000\aX\276W\000\000\000\000\aX\276W\000\000\000\000\001\000\000\000\000\000\000\000\360\070ٶkU\000\000\000\032K\270kU\000", time_sent = 1472092167, src_slot = 3, 
          worker_generation = 0, code = 6 '\006'}
        c = 0x556bb8288090
        ev = 0x556bb8377e60
#9  0x0000556bb6c7aba3 in ngx_event_process_posted (
    cycle=cycle@entry=0x556bb80c7170, 
    posted=0x556bb7285330 <ngx_posted_events>)
    at src/event/ngx_event_posted.c:33
        q = 0x556bb8377eb0
        ev = 0x556bb8377e60
#10 0x0000556bb6c7a65e in ngx_process_events_and_timers (
    cycle=cycle@entry=0x556bb80c7170) at src/event/ngx_event.c:259
        flags = <optimized out>
        timer = <optimized out>
        delta = <optimized out>
#11 0x0000556bb6c82625 in ngx_worker_process_cycle (
    cycle=cycle@entry=0x556bb80c7170, data=data@entry=0x2)
    at src/os/unix/ngx_process_cycle.c:753
        worker = 2
#12 0x0000556bb6c8100a in ngx_spawn_process (
    cycle=cycle@entry=0x556bb80c7170, 
    proc=proc@entry=0x556bb6c825d0 <ngx_worker_process_cycle>, 
    data=data@entry=0x2, name=name@entry=0x556bb6d98c02 "worker process", 
    respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = 2
#13 0x0000556bb6c828d0 in ngx_start_worker_processes (
    cycle=cycle@entry=0x556bb80c7170, n=4, type=type@entry=-3)
    at src/os/unix/ngx_process_cycle.c:358
        i = 2
        ch = {command = 1, pid = 16023, slot = 1, fd = 25}
#14 0x0000556bb6c836ef in ngx_master_process_cycle (cycle=0x556bb80c7170)
    at src/os/unix/ngx_process_cycle.c:130
        title = 0x556bb81c3e04 "master process /usr/sbin/nginx -g daemon on; master_process on;"
        p = <optimized out>
        size = <optimized out>
        i = <optimized out>
        n = <optimized out>
        sigio = <optimized out>
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 0}, it_value = {
            tv_sec = 0, tv_usec = 0}}
        live = <optimized out>
        delay = <optimized out>
        ls = <optimized out>
        ccf = 0x556bb80c8f10
#15 0x0000556bb6c5b081 in main (argc=<optimized out>, argv=<optimized out>)
    at src/core/nginx.c:367
        b = <optimized out>
        log = <optimized out>
        i = <optimized out>
        cycle = 0x556bb80c7170
        init_cycle = {conf_ctx = 0x0, pool = 0x556bb80c6b60, 
          log = 0x556bb701fd20 <ngx_log>, new_log = {log_level = 0, 
            file = 0x0, connection = 0, disk_full_time = 0, handler = 0x0, 
            data = 0x0, writer = 0x0, wdata = 0x0, action = 0x0, 
            next = 0x0}, log_use_stderr = 0, files = 0x0, 
          free_connections = 0x0, free_connection_n = 0, modules = 0x0, 
          modules_n = 0, modules_used = 0, reusable_connections_queue = {
            prev = 0x0, next = 0x0}, listening = {elts = 0x0, nelts = 0, 
            size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, 
            nelts = 0, size = 0, nalloc = 0, pool = 0x0}, config_dump = {
            elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, 
          open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, 
              next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, 
          shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, 
              next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, 
          connection_n = 0, files_n = 0, connections = 0x0, 
          read_events = 0x0, write_events = 0x0, old_cycle = 0x0, 
          conf_file = {len = 21, 
            data = 0x556bb6d93dbc "/etc/nginx/nginx.conf"}, conf_param = {
            len = 29, data = 0x7ffdc4270f53 "ss"}, conf_prefix = {len = 11, 
            data = 0x556bb6d93dbc "/etc/nginx/nginx.conf"}, prefix = {
            len = 17, data = 0x556bb6d93daa "/usr/share/nginx/"}, 
          lock_file = {len = 0, data = 0x0}, hostname = {len = 0, 
            data = 0x0}}
        cd = <optimized out>
        ccf = 0x556bb80c8f10
```

**Comment by slact** [comment]
Would it be possible for me to examine the coredump? From the looks of it, I'm guessing Nchan tried to output to an already-disconnected websocket subscriber, which is pretty weird.

**Comment by bymaximus** [comment]
Sure, attached core dump file. Yes, it seems problem is related to sending data to disconnect websocket.

I current have this scenario:

```
        nchan_redis_url redis://127.0.0.1:6379/0;
        nchan_use_redis on;
        nchan_subscriber_first_message newest;
        nchan_store_messages off;
        nchan_message_timeout 1s;
        nchan_redis_idle_channel_cache_timeout 5s;
        nchan_redis_ping_interval 10s;
        nchan_channel_timeout 3s;
        location = /nchanStatus {
                access_log off;
                add_header Refresh 1;
                nchan_stub_status;
        }
        location = /postCondition {
                access_log off;
                if ($request_method = 'GET') {
                        nchan_publisher http;
                        nchan_channel_id "$arg_channel";
                }
        }
        location = /post {
                if ($request_method = 'GET') {
                        return 405;
                }
                eval_subrequest_in_memory off;
                eval_buffer_size 4k;
                eval_override_content_type text/plain;
                eval $channelStatus {
                        proxy_connect_timeout 5s;
                        proxy_read_timeout 10s;
                        proxy_send_timeout 10s;
                        proxy_method GET;
                        proxy_pass_request_headers off;
                        proxy_pass_request_body off;
                        proxy_set_header Host XXXX;
                        proxy_set_header Accept text/json;
                        proxy_set_header Connection close;
                        proxy_pass "http://127.0.0.1/postCondition?channel=$arg_channel";
                }
                if ($channelStatus = '') {
                        return 204;
                }
                if ($channelStatus ~ '"subscribers": 0,') {
                        return 204;
                }
                if ($channelStatus ~ '"subscribers": ([1-9]+),') {
                        nchan_publisher http;
                        nchan_channel_id "$arg_channel";
                }
        }
        location ~ /postedData/(\w+)$ {
                access_log off;
                nchan_channel_id "$1";
                nchan_websocket_ping_interval 5s;
                nchan_subscriber websocket;
        }
```

When it is started, nchan have this status
```
total published messages: 0
stored messages: 0
shared memory used: 12K
channels: 0
subscribers: 0
redis pending commands: 0
redis connected servers: 4
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```

Nginx get tons of requests to POST messages to channel, but it only posts if channel exists and have at least one subscriber, so, it ignores all messages until I start a websocket subscriber connection.

Then it start POSTing messages normally, after some time websocket connection drops ```echo-protocol Connection Closed``` and nchan status change to something like this (notice redis connections):
```
total published messages: 465
stored messages: 47 <===== NORMAL WHEN nchan_store_messages are OFF?
shared memory used: 396K
channels: 1
subscribers: 0  <==== WEBSOCKET CONNECTION DROPPED
redis pending commands: 0
redis connected servers: 5 <==== NOT SURE WHY INCREASED, NGINX WORKERS ARE 4
total interprocess alerts received: 135 <====HIGH ALERTS IS NORMAL?
interprocess alerts in transit: 311
interprocess queued alerts: 311
total interprocess send delay: 0
total interprocess receive delay: 0
```

Then nginx server start getting stuck, I can call a curl GET to publisher end point which returns channel status but I cant POST, it loads forever, websocket subscriber connect but doesnt get any message if I reconnect it after connection drop.

[core.zip](https://github.com/slact/nchan/files/437519/core.zip)

**Comment by slact** [comment]
Haven't looked at the core yet (I'm probably going to need more info from you for that), but let me address the other part of your question:

```
total published messages: 465
stored messages: 47 <===== NORMAL WHEN nchan_store_messages are OFF?
  Yes, the messages are still buffered internally. They should be deleted within 10-20 seconds.
shared memory used: 396K
channels: 1
subscribers: 0  <==== WEBSOCKET CONNECTION DROPPED
redis pending commands: 0
redis connected servers: 5 <==== NOT SURE WHY INCREASED, NGINX WORKERS ARE 4
  because there was a crash and the disconnect from the crashed worker was not recorded
total interprocess alerts received: 135 <====HIGH ALERTS IS NORMAL?
  yes. This can be in the millions.
interprocess alerts in transit: 311
  This is probably frozen due to the crashed worker. 
interprocess queued alerts: 311
total interprocess send delay: 0
total interprocess receive delay: 0
```

**Comment by slact** [comment]
Ok, I understand what's happening here. Will have a fix shortly.

**Comment by bymaximus** [comment]
Awesome news, thank you for your effort you doing with nchan

**Comment by slact** [comment]
Fixed in 3729fc7. The issue was incorrect handling of a publisher's connection after a POST request that terminates before receiving a response.

**Comment by bymaximus** [comment]
Thank you, I will update and test, I still have some other strange behaviors which can be related or not. I will update once I have some status.

**Comment by slact** [comment]
Closing this, please reopen if you're still having issues.

**Comment by bymaximus** [comment]
Still getting some core dump
```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/nginx...done.
[New LWP 29953]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                           '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  publish_callback (status=9000, ch=0x7ffdc886cbe0, cln=0x555f4a4053b8) at /root/nchan-master/src/nchan_module.c:415
415	  ngx_http_request_t    *r = *rptr;

Thread 1 (Thread 0x7f1bf756b740 (LWP 29953)):
#0  publish_callback (status=9000, ch=0x7ffdc886cbe0, cln=0x555f4a4053b8) at /root/nchan-master/src/nchan_module.c:415
        ctx = <optimized out>
        empty_msgid = {time = 0, tag = {fixed = {0, 0, 0, 0}, allocd = 0x0}, tagactive = 0, tagcount = 0}
        rptr = 0x0
        r = <optimized out>
#1  0x0000555f489da2f2 in redisPublishCallback (c=0x555f4a25ca80, r=0x555f4a3c7b60, privdata=0x555f4a260aa0)
    at /root/nchan-master/src/store/redis/rdsstore.c:2686
        d = 0x555f4a260aa0
        reply = 0x555f4a3c7b60
        cur = <optimized out>
        ch = {id = {len = 0, data = 0x0}, messages = 0, subscribers = 35, last_seen = 1472665193, expires = 1472665194, last_published_msg_id = {
            time = 1472665193, tag = {fixed = {34, 0, 0, 0}, allocd = 0x22}, tagactive = 0, tagcount = 1}}
        rdata = 0x555f4a23df08
#2  0x0000555f489ce35f in __redisRunCallback (cb=0x7ffdc886cca0, cb=0x7ffdc886cca0, reply=<optimized out>, ac=0x555f4a25ca80)
    at /root/nchan-master/src/hiredis/async.c:269
        c = 0x555f4a25ca80
#3  redisProcessCallbacks (ac=0x555f4a25ca80) at /root/nchan-master/src/hiredis/async.c:469
        c = 0x555f4a25ca80
        cb = {next = 0x555f4a274690, fn = 0x555f489da180 <redisPublishCallback>, privdata = 0x555f4a260aa0}
        reply = 0x555f4a3c7b60
        status = <optimized out>
        __PRETTY_FUNCTION__ = "redisProcessCallbacks"
#4  0x0000555f489dee27 in redis_nginx_read_event (ev=0x555f4a2d5e60) at /root/nchan-master/src/store/redis/redis_nginx_adapter.c:145
        ac = 0x555f4a25ca80
        bytes_left = 21855
#5  0x0000555f488d1dd3 in ngx_event_process_posted (cycle=cycle@entry=0x555f4a0db170, posted=0x555f48edf3b0 <ngx_posted_events>)
    at src/event/ngx_event_posted.c:33
        q = 0x555f4a2d5eb0
        ev = 0x555f4a2d5e60
#6  0x0000555f488d188e in ngx_process_events_and_timers (cycle=cycle@entry=0x555f4a0db170) at src/event/ngx_event.c:259
        flags = <optimized out>
        timer = <optimized out>
        delta = <optimized out>
#7  0x0000555f488d9855 in ngx_worker_process_cycle (cycle=cycle@entry=0x555f4a0db170, data=data@entry=0x5) at src/os/unix/ngx_process_cycle.c:753
        worker = 5
#8  0x0000555f488d823a in ngx_spawn_process (cycle=cycle@entry=0x555f4a0db170, proc=proc@entry=0x555f488d9800 <ngx_worker_process_cycle>, 
    data=data@entry=0x5, name=name@entry=0x555f489f24c2 "worker process", respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = 5
#9  0x0000555f488d9b00 in ngx_start_worker_processes (cycle=cycle@entry=0x555f4a0db170, n=8, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:358
        i = 5
        ch = {command = 1, pid = 29952, slot = 4, fd = 43}
#10 0x0000555f488da91f in ngx_master_process_cycle (cycle=0x555f4a0db170) at src/os/unix/ngx_process_cycle.c:130
        title = 0x555f4a208d6c "master process /usr/sbin/nginx -g daemon on; master_process on;"
        p = <optimized out>
        size = <optimized out>
        i = <optimized out>
        n = <optimized out>
        sigio = <optimized out>
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 0}, it_value = {tv_sec = 0, tv_usec = 0}}
        live = <optimized out>
        delay = <optimized out>
        ls = <optimized out>
        ccf = 0x555f4a0dcf10
#11 0x0000555f488b22b1 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:367
        b = <optimized out>
        log = <optimized out>
        i = <optimized out>
        cycle = 0x555f4a0db170
        init_cycle = {conf_ctx = 0x0, pool = 0x555f4a0dab60, log = 0x555f48c79d60 <ngx_log>, new_log = {log_level = 0, file = 0x0, connection = 0, 
            disk_full_time = 0, handler = 0x0, data = 0x0, writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0}, log_use_stderr = 0, files = 0x0, 
          free_connections = 0x0, free_connection_n = 0, modules = 0x0, modules_n = 0, modules_used = 0, reusable_connections_queue = {prev = 0x0, 
            next = 0x0}, listening = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, 
            pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, 
              next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, 
            nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0, read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {
            len = 21, data = 0x555f489ed65c "/etc/nginx/nginx.conf"}, conf_param = {len = 29, data = 0x7ffdc886df53 "ss"}, conf_prefix = {len = 11, 
            data = 0x555f489ed65c "/etc/nginx/nginx.conf"}, prefix = {len = 17, data = 0x555f489ed64a "/usr/share/nginx/"}, lock_file = {len = 0, 
            data = 0x0}, hostname = {len = 0, data = 0x0}}
        cd = <optimized out>
        ccf = 0x555f4a0dcf10
[core.zip](https://github.com/slact/nchan/files/447939/core.zip)

```
