### ISSUE TITLE
Possible crash after publisher GET, POST, or DELETE then disconnecting before response

### ISSUE THREAD

**Issue by bymaximus** [slact/nchan#246]
Still getting some core dump (related to #235 , cant reopen)

```shell
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/nginx...done.
[New LWP 29953]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                           '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  publish_callback (status=9000, ch=0x7ffdc886cbe0, cln=0x555f4a4053b8) at /root/nchan-master/src/nchan_module.c:415
415	  ngx_http_request_t    *r = *rptr;

Thread 1 (Thread 0x7f1bf756b740 (LWP 29953)):
#0  publish_callback (status=9000, ch=0x7ffdc886cbe0, cln=0x555f4a4053b8) at /root/nchan-master/src/nchan_module.c:415
        ctx = <optimized out>
        empty_msgid = {time = 0, tag = {fixed = {0, 0, 0, 0}, allocd = 0x0}, tagactive = 0, tagcount = 0}
        rptr = 0x0
        r = <optimized out>
#1  0x0000555f489da2f2 in redisPublishCallback (c=0x555f4a25ca80, r=0x555f4a3c7b60, privdata=0x555f4a260aa0)
    at /root/nchan-master/src/store/redis/rdsstore.c:2686
        d = 0x555f4a260aa0
        reply = 0x555f4a3c7b60
        cur = <optimized out>
        ch = {id = {len = 0, data = 0x0}, messages = 0, subscribers = 35, last_seen = 1472665193, expires = 1472665194, last_published_msg_id = {
            time = 1472665193, tag = {fixed = {34, 0, 0, 0}, allocd = 0x22}, tagactive = 0, tagcount = 1}}
        rdata = 0x555f4a23df08
#2  0x0000555f489ce35f in __redisRunCallback (cb=0x7ffdc886cca0, cb=0x7ffdc886cca0, reply=<optimized out>, ac=0x555f4a25ca80)
    at /root/nchan-master/src/hiredis/async.c:269
        c = 0x555f4a25ca80
#3  redisProcessCallbacks (ac=0x555f4a25ca80) at /root/nchan-master/src/hiredis/async.c:469
        c = 0x555f4a25ca80
        cb = {next = 0x555f4a274690, fn = 0x555f489da180 <redisPublishCallback>, privdata = 0x555f4a260aa0}
        reply = 0x555f4a3c7b60
        status = <optimized out>
        __PRETTY_FUNCTION__ = "redisProcessCallbacks"
#4  0x0000555f489dee27 in redis_nginx_read_event (ev=0x555f4a2d5e60) at /root/nchan-master/src/store/redis/redis_nginx_adapter.c:145
        ac = 0x555f4a25ca80
        bytes_left = 21855
#5  0x0000555f488d1dd3 in ngx_event_process_posted (cycle=cycle@entry=0x555f4a0db170, posted=0x555f48edf3b0 <ngx_posted_events>)
    at src/event/ngx_event_posted.c:33
        q = 0x555f4a2d5eb0
        ev = 0x555f4a2d5e60
#6  0x0000555f488d188e in ngx_process_events_and_timers (cycle=cycle@entry=0x555f4a0db170) at src/event/ngx_event.c:259
        flags = <optimized out>
        timer = <optimized out>
        delta = <optimized out>
#7  0x0000555f488d9855 in ngx_worker_process_cycle (cycle=cycle@entry=0x555f4a0db170, data=data@entry=0x5) at src/os/unix/ngx_process_cycle.c:753
        worker = 5
#8  0x0000555f488d823a in ngx_spawn_process (cycle=cycle@entry=0x555f4a0db170, proc=proc@entry=0x555f488d9800 <ngx_worker_process_cycle>, 
    data=data@entry=0x5, name=name@entry=0x555f489f24c2 "worker process", respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = 5
#9  0x0000555f488d9b00 in ngx_start_worker_processes (cycle=cycle@entry=0x555f4a0db170, n=8, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:358
        i = 5
        ch = {command = 1, pid = 29952, slot = 4, fd = 43}
#10 0x0000555f488da91f in ngx_master_process_cycle (cycle=0x555f4a0db170) at src/os/unix/ngx_process_cycle.c:130
        title = 0x555f4a208d6c "master process /usr/sbin/nginx -g daemon on; master_process on;"
        p = <optimized out>
        size = <optimized out>
        i = <optimized out>
        n = <optimized out>
        sigio = <optimized out>
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 0}, it_value = {tv_sec = 0, tv_usec = 0}}
        live = <optimized out>
        delay = <optimized out>
        ls = <optimized out>
        ccf = 0x555f4a0dcf10
#11 0x0000555f488b22b1 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:367
        b = <optimized out>
        log = <optimized out>
        i = <optimized out>
        cycle = 0x555f4a0db170
        init_cycle = {conf_ctx = 0x0, pool = 0x555f4a0dab60, log = 0x555f48c79d60 <ngx_log>, new_log = {log_level = 0, file = 0x0, connection = 0, 
            disk_full_time = 0, handler = 0x0, data = 0x0, writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0}, log_use_stderr = 0, files = 0x0, 
          free_connections = 0x0, free_connection_n = 0, modules = 0x0, modules_n = 0, modules_used = 0, reusable_connections_queue = {prev = 0x0, 
            next = 0x0}, listening = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, 
            pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, 
              next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, 
            nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0, read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {
            len = 21, data = 0x555f489ed65c "/etc/nginx/nginx.conf"}, conf_param = {len = 29, data = 0x7ffdc886df53 "ss"}, conf_prefix = {len = 11, 
            data = 0x555f489ed65c "/etc/nginx/nginx.conf"}, prefix = {len = 17, data = 0x555f489ed64a "/usr/share/nginx/"}, lock_file = {len = 0, 
            data = 0x0}, hostname = {len = 0, data = 0x0}}
        cd = <optimized out>
        ccf = 0x555f4a0dcf10
```

[core.zip](https://github.com/slact/nchan/files/447939/core.zip)

**Comment by slact** [comment]
What OS is this on? I'm having trouble testing this because after terminating a publisher connection it's still available for a time in a TIME_WAIT state, thus failing to trigger this crash.

**Comment by slact** [comment]
Nevermind, I'm able to reproduce this with a hack to the nginx code. I still want to know what OS you're using so that I could reproduce it in the wild. I'll update with a fix shortly.

**Comment by slact** [comment]
fixed in c14eac6

**Comment by bymaximus** [comment]
Sorry for delay, is ubuntu server 14.04

**Comment by slact** [comment]
Ok, thanks.

**Comment by bymaximus** [comment]
Hooah!

Seems working fine now, got it running ~30min, no errors. Thank you

total published messages: 16711
stored messages: 16895
shared memory used: 400K
channels: 1
subscribers: 2
redis pending commands: 0
redis connected servers: 8
total interprocess alerts received: 51184
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0

**Comment by slact** [comment]
Excellent. Thanks for the follow-up. Expect a version bump in the next few days.
