### ISSUE TITLE
segfault in nchan_memstore_handle_get_message_reply (memstore.c:2732)

### ISSUE THREAD

**Issue by caseyf** [slact/nchan#362]
I just had this crash.

(This is nchan 6cd0834a2886b2033d8a8d7529dcd0905e1baff0)

core + binary: https://github.com/caseyf/nchan-coredump/raw/master/issue-362.tar.bz2

```
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000506e39 in nchan_memstore_handle_get_message_reply (msg=0x0, findmsg_status=MSG_EXPECTED,
    data=0x344c5c0) at /usr/local/src/nchan-20170505/src/store/memory/memstore.c:2732
2732	  d->cb(findmsg_status, msg, d->cb_privdata);



#0  0x0000000000506e39 in nchan_memstore_handle_get_message_reply (msg=0x0, findmsg_status=MSG_EXPECTED,
    data=0x344c5c0) at /usr/local/src/nchan-20170505/src/store/memory/memstore.c:2732
#1  0x00000000004fae19 in receive_get_message_reply (sender=4, d=0x7fff6b6a0ef0)
    at /usr/local/src/nchan-20170505/src/store/memory/ipc-handlers.c:523
#2  0x00000000004fc62d in memstore_ipc_alert_handler (sender=4, code=8, data=0x7fff6b6a0ef0)
    at /usr/local/src/nchan-20170505/src/store/memory/ipc-handlers.c:931
#3  0x00000000004f8f44 in ipc_read_handler (ev=0x7fedd3fe5310)
    at /usr/local/src/nchan-20170505/src/store/memory/ipc.c:457
#4  0x000000000045802d in ngx_epoll_process_events (cycle=0xb60450, timer=500, flags=1)
    at src/event/modules/ngx_epoll_module.c:902
#5  0x0000000000449a66 in ngx_process_events_and_timers (cycle=0xb60450) at src/event/ngx_event.c:242
#6  0x0000000000455dce in ngx_worker_process_cycle (cycle=0xb60450, data=0x7) at src/os/unix/ngx_process_cycle.c:749
#7  0x0000000000452c3f in ngx_spawn_process (cycle=0xb60450, proc=0x455d1d <ngx_worker_process_cycle>, data=0x7,
    name=0x52a1b0 "worker process", respawn=7) at src/os/unix/ngx_process.c:198
#8  0x00000000004558b9 in ngx_reap_children (cycle=0xb60450) at src/os/unix/ngx_process_cycle.c:621
#9  0x0000000000454873 in ngx_master_process_cycle (cycle=0xb60450) at src/os/unix/ngx_process_cycle.c:174
#10 0x0000000000417e46 in main (argc=3, argv=0x7fff6b6a1608) at src/core/nginx.c:375

**Comment by slact** [comment]
It looks like this was a followup crash after an immediately previous one. Do  you see any prior crashes in your nginx error log?

**Comment by caseyf** [comment]
nuts. I didn't save the log and this is the only core that was dumped. dmesg does show that I had a hundred or so segfaults in different processes.

**Comment by slact** [comment]
I have code queued up that makes Nchan not go off the rails if one worker crashes. It has a big change in it though -- the IPC code got a complete overhaul, so it's not ready for release yet. For now, I recommend you have a corepattern that drops a file with a timestamp, process id, and so on, so that it doesn't overwrite the previous core. I can help you set that up if you want.

**Comment by caseyf** [comment]
ok - I think I have the core that you need, messaging a link

**Comment by slact** [comment]
fixed in another issue. closing.
