### ISSUE TITLE
Publisher GET response data incorrect when using Redis

### ISSUE THREAD

**Issue by kilgor** [slact/nchan#412]
Documentation said:
```
HTTP GET requests return channel information without publishing a message. The response code is 200 if the channel exists, and 404 otherwise:
> curl -v --request GET -H "Accept: text/json" http://127.0.0.2:80/pub

 {"messages": 1, "requested": 7, "subscribers": 0, "last_message_id": "1450755421:0" }
```

I use redis backend.
When i make GET request do publisher endpoint i get
```
curl -s -X GET -H "Accept: text/json" 'http://127.0.0.1/pub?id=test'
{messages: 4, requested: -1, subscribers: 36042, last_message_id: 0:0 }
```

Paramaters requested and last_message_id is wrong. 
Posting msg via POST to channel return correct result

**Comment by slact** [comment]
fixed in 894d3b32029e0a65b4

**Comment by kilgor** [comment]
Thanks @slact but i have next issue. Reloading nginx with signal HUP leaves subscribers counter in nchan_stub_status and adds new value (duplicate)

In publisher GET value increase more because redis save it and each worker (currently i have 3) leaves his value and added new one.

Restart nginx helps with nchan_stub_status but in publisher subscribers counter still increase.

Reload is more important problem because debian reload nginx each day to rotate logs

**Comment by kilgor** [comment]
During reload i get seg fault

```
#0  0x000000000041410f in ngx_log_error_core (level=8, log=0x1, err=0, fmt=0x7feccd819060 "event timer del: %d: %M") at src/core/ngx_log.c:163
#1  0x00007feccd7fecf5 in ngx_event_del_timer (ev=0x26bd910) at src/event/ngx_event_timer.h:34
#2  0x00007feccd7fffbb in rdt_set_status (rdata=0x26bd778, status=DISCONNECTED, ac=0x26f6e50) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/redis/rdsstore.c:425
#3  0x00007feccd801332 in redis_nginx_disconnect_event_handler (ac=0x26f6e50, status=0) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/redis/rdsstore.c:742
#4  0x00007feccd7f0ae0 in __redisAsyncFree (ac=0x26f6e50) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/hiredis/async.c:311
#5  0x00007feccd7f0bdc in __redisAsyncDisconnect (ac=0x26f6e50) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/hiredis/async.c:348
#6  0x00007feccd7f0c38 in redisAsyncDisconnect (ac=0x26f6e50) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/hiredis/async.c:361
#7  0x00007feccd80ac1e in redis_nginx_force_close_context (context=0x26bd7d8) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/redis/redis_nginx_adapter.c:127
#8  0x00007feccd808e42 in redis_data_tree_exiter_stage2 (seed=0x7feccdcc8240 <redis_data_tree>, rdata=0x26bd778, chanheads=0x7ffd059a6e44)
    at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/redis/rdsstore.c:2655
#9  0x00007feccd7b7008 in rbtree_walk_real (seed=0x7feccdcc8240 <redis_data_tree>, node=0x26bd750, sentinel=0x7feccdcc8260 <redis_data_tree+32>, callback=0x7feccd808de8 <redis_data_tree_exiter_stage2>, data=0x7ffd059a6e44)
    at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/util/nchan_rbtree.c:227
#10 0x00007feccd7b7185 in rbtree_walk (seed=0x7feccdcc8240 <redis_data_tree>, callback=0x7feccd808de8 <redis_data_tree_exiter_stage2>, data=0x7ffd059a6e44)
    at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/util/nchan_rbtree.c:255
#11 0x00007feccd80912d in nchan_store_exit_worker (cycle=0x26a14e0) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/redis/rdsstore.c:2705
#12 0x00007feccd7b0644 in nchan_exit_worker (cycle=0x26a14e0) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/nchan_setup.c:752
#13 0x0000000000458c16 in ngx_worker_process_exit (cycle=0x26a14e0) at src/os/unix/ngx_process_cycle.c:952
#14 0x0000000000458224 in ngx_worker_process_cycle (cycle=0x26a14e0, data=0x1) at src/os/unix/ngx_process_cycle.c:743
#15 0x00000000004548c8 in ngx_spawn_process (cycle=0x26a14e0, proc=0x458182 <ngx_worker_process_cycle>, data=0x1, name=0x516deb "worker process", respawn=-4) at src/os/unix/ngx_process.c:198
#16 0x0000000000456fc6 in ngx_start_worker_processes (cycle=0x26a14e0, n=3, type=-4) at src/os/unix/ngx_process_cycle.c:358
#17 0x0000000000456b01 in ngx_master_process_cycle (cycle=0x26a14e0) at src/os/unix/ngx_process_cycle.c:243
#18 0x000000000041171f in main (argc=3, argv=0x7ffd059a7498) at src/core/nginx.c:375
```

**Comment by slact** [comment]
@kilgor: closing this, as the original issue was fixed. Please open another ticket if you're still having an issue with the counts being incorrect after reloading.
