### ISSUE TITLE
Segmentation fault in nchan_store_subscribe_channel_existence_check_callback

### ISSUE THREAD

**Issue by kilgor** [slact/nchan#471]
The bug occures after sending big message to 20k connected users.
nginx version: nginx/1.12.2
built with OpenSSL 1.0.2l  25 May 2017
TLS SNI support enabled
nchan last master version

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6c60abfd44 in nchan_store_subscribe_channel_existence_check_callback (channel_status=1, _=0x0, d=0xfdc3170) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/memory/memstore.c:2140
2140      if(d->sub->fn->release(d->sub, 0) == NGX_OK) {
(gdb) bt
#0  0x00007f6c60abfd44 in nchan_store_subscribe_channel_existence_check_callback (channel_status=1, _=0x0, d=0xfdc3170) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/memory/memstore.c:2140
#1  0x00007f6c60ab5e1a in receive_channel_auth_check_reply (sender=0, d=0x7fff312702e0) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/memory/ipc-handlers.c:867
#2  0x00007f6c60ab6ade in memstore_ipc_alert_handler (sender=0, code=16, data=0x7fff312702e0) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/memory/ipc-handlers.c:1062
#3  0x00007f6c60ab2588 in ipc_read_handler (ev=0x7f6c55a5b190) at /usr/local/src/nginx/build/nginx-1.12.2/debian/modules/nchan-nginx-module/src/store/memory/ipc.c:457
#4  0x000000000045b0b8 in ngx_epoll_process_events (cycle=0x1579720, timer=600, flags=1) at src/event/modules/ngx_epoll_module.c:902
#5  0x0000000000448372 in ngx_process_events_and_timers (cycle=0x1579720) at src/event/ngx_event.c:242
#6  0x0000000000458269 in ngx_worker_process_cycle (cycle=0x1579720, data=0x2) at src/os/unix/ngx_process_cycle.c:749
#7  0x00000000004548c8 in ngx_spawn_process (cycle=0x1579720, proc=0x458182 <ngx_worker_process_cycle>, data=0x2, name=0x516deb "worker process", respawn=2) at src/os/unix/ngx_process.c:198
#8  0x0000000000457cfe in ngx_reap_children (cycle=0x1579720) at src/os/unix/ngx_process_cycle.c:621
#9  0x0000000000456802 in ngx_master_process_cycle (cycle=0x1579720) at src/os/unix/ngx_process_cycle.c:174
#10 0x000000000041171f in main (argc=3, argv=0x7fff31270a08) at src/core/nginx.c:375
```

**Comment by slact** [comment]
what Nchan version?
