### ISSUE TITLE
Redis-related segfault (v1.2.6)

### ISSUE THREAD

**Issue by slact** [slact/nchan#558]
```
#0  ngx_rbtree_insert_timer_value (temp=0x6435303337656633, node=0x7fe2f6a55378, sentinel=0x750400 <ngx_event_timer_sentinel>) at src/core/ngx_rbtree.c:139
        p = <optimized out>
#1  0x0000000000428d93 in ngx_rbtree_insert (tree=0xa2e820 <ngx_event_timer_rbtree>, node=node@entry=0x7fe2f6a55378) at src/core/ngx_rbtree.c:44
        root = 0xa2e820 <ngx_event_timer_rbtree>
        temp = <optimized out>
        sentinel = 0x750400 <ngx_event_timer_sentinel>
#2  0x0000000000457c7a in ngx_event_add_timer (timer=<optimized out>, ev=0x7fe2f6a55350) at src/event/ngx_event_timer.h:84
        key = 11606781554
        diff = <optimized out>
#3  ngx_http_set_keepalive (r=<optimized out>) at src/http/ngx_http_request.c:3103
        tcp_nodelay = <optimized out>
        b = <optimized out>
        f = <optimized out>
        cl = <optimized out>
        ln = <optimized out>
        rev = 0x7fe2f6a55350
        wev = <optimized out>
        c = <optimized out>
        hc = 0x13a9f80
        clcf = 0x137d368
#4  0x0000000000457e23 in ngx_http_finalize_connection (r=<optimized out>, r@entry=0x3c1c350) at src/http/ngx_http_request.c:2618
        clcf = 0x137d368
#5  0x000000000045833e in ngx_http_finalize_request (r=0x3c1c350, rc=<optimized out>) at src/http/ngx_http_request.c:2510
        c = 0x7fe2f73b9540
        pr = <optimized out>
        clcf = <optimized out>
#6  0x00000000004acfd3 in nchan_http_finalize_request (r=r@entry=0x3c1c350, code=<optimized out>) at /tmp/nchan/src/util/nchan_output.c:668
No locals.
#7  0x00000000004a09af in publish_callback (status=9000, data=0x7fffcf2f6420, pd=<optimized out>) at /tmp/nchan/src/nchan_module.c:764
        ctx = 0x3c1d1f0
        empty_msgid = {time = 0, tag = {fixed = {0, 0, 0, 0}, allocd = 0x0}, tagactive = 0, tagcount = 0}
        ch = 0x7fffcf2f6420
        r = 0x3c1c350
#8  0x00000000004e377f in redisPublishNostoreCallback (c=0x13595c0, r=<optimized out>, privdata=0x203aaf0) at /tmp/nchan/src/store/redis/rdsstore.c:2340
        d = 0x203aaf0
        reply = <optimized out>
        els = <optimized out>
        ch = {id = {len = 0, data = 0x0}, messages = 0, subscribers = 1, last_seen = 0, expires = 0, last_published_msg_id = {time = 0, tag = {fixed = {0, 0, 0, 0}, allocd = 0x0}, tagactive = 0, 
            tagcount = 0}}
        node = <optimized out>
#9  0x00000000004d3509 in __redisRunCallback (ac=ac@entry=0x13595c0, cb=cb@entry=0x7fffcf2f64b0, reply=<optimized out>) at /tmp/nchan/src/store/redis/hiredis/async.c:269
        c = 0x13595c0
#10 0x00000000004d45be in redisProcessCallbacks (ac=ac@entry=0x13595c0) at /tmp/nchan/src/store/redis/hiredis/async.c:469
        c = 0x13595c0
        cb = {next = 0x0, fn = 0x4e3646 <redisPublishNostoreCallback>, privdata = 0x203aaf0}
        reply = 0x16fe430
        status = 0
        __PRETTY_FUNCTION__ = "redisProcessCallbacks"
#11 0x00000000004d4691 in redisAsyncHandleRead (ac=ac@entry=0x13595c0) at /tmp/nchan/src/store/redis/hiredis/async.c:533
        c = 0x13595c0
#12 0x00000000004e64f6 in redis_nginx_read_event (ev=0x7fe2f6a532b0) at /tmp/nchan/src/store/redis/redis_nginx_adapter.c:143
        ac = 0x13595c0
        fd = 28
        bytes_left = 0
#13 0x0000000000443e0b in ngx_epoll_process_events (cycle=<optimized out>, timer=<optimized out>, flags=1) at src/event/modules/ngx_epoll_module.c:902
        events = 1
        revents = 1
        instance = 0
        i = 0
        level = <optimized out>
        err = <optimized out>
        rev = <optimized out>
        wev = <optimized out>
        queue = <optimized out>
        c = 0x7fe2f73b4668
#14 0x000000000043af97 in ngx_process_events_and_timers (cycle=cycle@entry=0x1351180) at src/event/ngx_event.c:242
        flags = 1
        timer = 4
        delta = 11606706554
---Type <return> to continue, or q <return> to quit---
#15 0x000000000044239c in ngx_worker_process_cycle (cycle=cycle@entry=0x1351180, data=data@entry=0x1) at src/os/unix/ngx_process_cycle.c:750
        worker = 1
#16 0x00000000004406ed in ngx_spawn_process (cycle=cycle@entry=0x1351180, proc=proc@entry=0x442335 <ngx_worker_process_cycle>, data=data@entry=0x1, name=name@entry=0x4eb473 "worker process", 
    respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:199
        on = 1
        pid = 0
        s = 1
#17 0x0000000000441813 in ngx_start_worker_processes (cycle=cycle@entry=0x1351180, n=2, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:359
        i = 1
        ch = {command = 1, pid = 31309, slot = 0, fd = 3}
#18 0x0000000000442a90 in ngx_master_process_cycle (cycle=cycle@entry=0x1351180) at src/os/unix/ngx_process_cycle.c:131
        title = 0x1387af4 "master process /usr/local/nginx/sbin/nginx -c /etc/nginx/nginx-nchan.conf -g daemon on; master_process on;"
        p = <optimized out>
        size = 107
        i = 5
        n = <optimized out>
        sigio = <optimized out>
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 0}, it_value = {tv_sec = 0, tv_usec = 0}}
        live = <optimized out>
        delay = <optimized out>
        ls = <optimized out>
        ccf = 0x1352d08
#19 0x000000000041d6e3 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:382
        b = <optimized out>
        log = 0x74dcc0 <ngx_log>
        i = <optimized out>
        cycle = 0x1351180
        init_cycle = {conf_ctx = 0x0, pool = 0x1350b10, log = 0x74dcc0 <ngx_log>, new_log = {log_level = 0, file = 0x0, connection = 0, disk_full_time = 0, handler = 0x0, data = 0x0, writer = 0x0, 
            wdata = 0x0, action = 0x0, next = 0x0}, log_use_stderr = 0, files = 0x0, free_connections = 0x0, free_connection_n = 0, modules = 0x0, modules_n = 0, modules_used = 0, 
          reusable_connections_queue = {prev = 0x0, next = 0x0}, reusable_connections_n = 0, listening = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, 
            nalloc = 0, pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, config_dump_rbtree = {root = 0x0, sentinel = 0x0, insert = 0x0}, config_dump_sentinel = {
            key = 0, left = 0x0, right = 0x0, parent = 0x0, color = 0 '\000', data = 0 '\000'}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, 
          shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0, read_events = 0x0, 
          write_events = 0x0, old_cycle = 0x0, conf_file = {len = 27, data = 0x7fffcf2f6f42 ""}, conf_param = {len = 29, data = 0x7fffcf2f6f61 ""}, conf_prefix = {len = 11, data = 0x7fffcf2f6f42 ""}, 
          prefix = {len = 17, data = 0x4e6fb6 "/usr/local/nginx/"}, lock_file = {len = 0, data = 0x0}, hostname = {len = 0, data = 0x0}}
        cd = <optimized out>
        ccf = <optimized out>
```

**Comment by slact** [comment]
(it's already fixed)
